### ISSUE TITLE
Accounting - Configuration - Can Create New Accounting Period Without Year

### ISSUE THREAD

**Issue by sam-adam** [sam-adam/Macsauto_w_Finance#15]
![image](https://cloud.githubusercontent.com/assets/2836541/5793496/f1373036-9f77-11e4-90a6-f4c896c4b65d.png)

**Comment by surwijaya12** [comment]
Ready to be tested (internal testing)

**Comment by sam-adam** [comment]
@surwijaya12 Belum ada commitan masuk gan

**Comment by sam-adam** [comment]
Fixed
