### ISSUE TITLE
Accounting - GL Account - Can Add Without Description And Ambiguous Error Message

### ISSUE THREAD

**Issue by sam-adam** [sam-adam/Macsauto_w_Finance#17]
Can add without desc: 
![image](https://cloud.githubusercontent.com/assets/2836541/5793515/0506d3c2-9f79-11e4-8bdd-39dead93fd80.png)

Ambiguous message:
![image](https://cloud.githubusercontent.com/assets/2836541/5793517/17424378-9f79-11e4-9320-3cfeba7244d6.png)

**Comment by surwijaya12** [comment]
Updated, ready to test

**Comment by sam-adam** [comment]
@surwijaya12 Masih ada beberapa bug gan:
Yang ini masih bisa di add / edit tanpa description:
![a](https://cloud.githubusercontent.com/assets/2836541/5886135/c6b54470-a3bd-11e4-9550-c4ed3d79bcb4.jpg)

Yang ini sepertinya waktu mau dideactivate baca GLNum nya dari label + textbox ya, harusnya emang gak ada yang diluar nomor branchnya sih tapi just in case aja dari selected cell aja mungkin gan:
![image](https://cloud.githubusercontent.com/assets/2836541/5886152/843596b2-a3be-11e4-8d49-21edeec72e4e.png)

Lalu fitur delete masih mau dikasih ya?

**Comment by surwijaya12** [comment]
Updated ya ,

itu fitur delete ma edit cm bs di pke klo blom ad transaksi ma skali,
incase bgt dia salah bwt aj, n biar ga byk data sampah :)

On Sat, Jan 24, 2015 at 11:50 AM, Samuel Adam Suhendra <
notifications@github.com> wrote:

> Assigned #17 https://github.com/sam-adam/Macsauto_w_Finance/issues/17
> to @surwijaya12 https://github.com/surwijaya12.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sam-adam/Macsauto_w_Finance/issues/17#event-224104489
> .

## 

Best Regards,

Surya Wijaya

**Comment by sam-adam** [comment]
Tested, issue pertama yang closed :+1:
