### ISSUE TITLE
Transaction - Cancel Transaction

### ISSUE THREAD

**Issue by sam-adam** [sam-adam/Macsauto_w_Finance#18]

**Comment by sam-adam** [comment]
@surwijaya12 Tolong ditesting ya gan

**Comment by surwijaya12** [comment]
ini ad error gini,
![image](https://cloud.githubusercontent.com/assets/10340720/6124396/b711c806-b13f-11e4-84d8-64d7c2d1d850.png)

**Comment by sam-adam** [comment]
@surwijaya12 Woke gan, updated ya tolong ditest lagi

**Comment by surwijaya12** [comment]
tested and works fine
